pom.xml
src/main/java/jenkins/branch/BranchProjectFactory.java
src/main/java/jenkins/branch/BranchProperty.java
src/main/java/jenkins/branch/BranchPropertyDescriptor.java
src/main/java/jenkins/branch/BranchPropertyStrategyDescriptor.java
src/main/java/jenkins/branch/BuildRetentionBranchProperty.java
src/main/java/jenkins/branch/DeadBranchStrategy.java
src/main/java/jenkins/branch/DeadBranchStrategyDescriptor.java
src/main/java/jenkins/branch/DefaultDeadBranchStrategy.java
src/main/java/jenkins/branch/DescriptorOrder.java
src/main/java/jenkins/branch/IndexAtLeastTrigger.java
src/main/java/jenkins/branch/JobDecorator.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/MultiBranchProjectDescriptor.java
src/main/java/jenkins/branch/ParameterDefinitionBranchProperty.java
src/main/java/jenkins/branch/ProjectDecorator.java
src/main/java/jenkins/branch/RateLimitBranchProperty.java
src/main/java/jenkins/branch/UntrustedBranchProperty.java
src/main/resources/jenkins/branch/DefaultBranchPropertyStrategy/config.jelly
src/main/resources/jenkins/branch/MultiBranchProject/configure-common.jelly
src/main/resources/jenkins/branch/ParameterDefinitionBranchProperty/config.jelly

[JENKINS-26129](https://issues.jenkins-ci.org/browse/JENKINS-26129)
Here I am just trying to make the minimal changes necessary to allow creation of a multibranch Workflow project type without being very disruptive for existing callers such as `literate`. It is not source compatible but so far it _seems_ binary compatible.

[JENKINS-26129] Prepare for multibranch workflows

---

src/main/java/jenkins/branch/MultiBranchProject.java

`MultiBranchProject` is a `FlyweightTask` so it does not require a heavyweight executor; it could “run” on any node, even `master` when configured to have zero executors. (At least as of JENKINS-7291 in 1.510.) In fact `BranchIndexing` was not doing anything at all with the `Computer` it was handed, other than using its `Charset`, which was probably wrong anyway.
For compatibility of old indexing logs I am retaining the `charset` field, in case it was “run on” a slave with a different charset than master (and there were non-ASCII branch names!), though I am tempted to just delete the field and hardcode `Charset.default()`.
Why do I care about this issue? It turned out there was a bug in `durable-task` which I will fix as a separate PR, and the combination of these two bugs prevented use …

Always run BranchIndexing on master

---

pom.xml
src/main/java/jenkins/branch/BranchProjectFactory.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/4.
@reviewbybees esp. @stephenc, @recena, @amuniz

[JENKINS-30595] Implemented API

---

src/main/java/jenkins/branch/Branch.java
src/main/java/jenkins/branch/BranchProjectFactory.java
src/main/java/jenkins/branch/MultiBranchProject.java

[JENKINS-30744](https://issues.jenkins-ci.org/browse/JENKINS-30744)
Yes, this is incompatible, but I see no way around that.

[JENKINS-30744] Introduced Branch.encodedName

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/jenkins/branch/MultibranchImplementationTest.java
src/test/java/jenkins/branch/harness/BranchProperty.java
src/test/java/jenkins/branch/harness/MultiBranchImpl.java

[JENKINS-31432](https://issues.jenkins-ci.org/browse/JENKINS-31432)
@reviewbybees

[JENKINS-31432] NPE on SCMSourceOwner.getSCMSources() call

---

src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java
src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java

[JENKINS-31949](https://issues.jenkins-ci.org/browse/JENKINS-31949)
@reviewbybees

[JENKINS-31949] CustomOrganizationFolderDescriptor.HideGeneric did not work inside folders

---

src/main/java/jenkins/branch/BranchSource.java
src/main/java/jenkins/branch/OrganizationFolder.java

Make BranchSource.strategy use @DataBoundSetter

---

pom.xml
src/main/resources/index.jelly

Adapt to Parent POM 2.3 and JTH 2.1.
@reviewbybees

[JENKINS-32493] Adapt to Parent POM 2.3.

---

pom.xml
src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java

[JENKINS-33106](https://issues.jenkins-ci.org/browse/JENKINS-33106)

[JENKINS-33106] Dynamic CustomOrganizationFolderDescriptor registration

---

src/main/java/jenkins/branch/BranchPropertyDescriptor.java
src/main/java/jenkins/branch/BranchPropertyStrategyDescriptor.java
src/main/resources/jenkins/branch/BranchSource/config.jelly
src/main/resources/lib/branch-api/dropdownDescriptorSelector.jelly

[JENKINS-32670](https://issues.jenkins-ci.org/browse/JENKINS-32670)
So, do not show any of the controls for setting branch properties (unless some other plugin adds some which do not get excluded).
@reviewbybees

[JENKINS-32670] Multibranch Pipelines have no applicable branch properties

---

pom.xml
src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java
src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java

[JENKINS-33808](https://issues.jenkins-ci.org/browse/JENKINS-33808)
downstream of https://github.com/jenkinsci/scm-api-plugin/pull/9
@reviewbybees especially @jglick

[JENKINS-33808] Support for Item categorization

---

src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.jelly
src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.properties

Follow-up to #29.
@reviewbybees

Documenting variables from ChangeRequestAction

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

@reviewbybees esp. @jglick since he noticed of this [bug](https://github.com/jenkinsci/branch-api-plugin/pull/38#discussion_r61626959)

Follow up #38

---

pom.xml

[JENKINS-34471] Fix PCT against core 2.0

---

pom.xml
src/main/java/jenkins/branch/OrganizationFolder.java

[JENKINS-33819](https://issues.jenkins-ci.org/browse/JENKINS-33819)
downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/61
@reviewbybees

[JENKINS-33819] OrphanedItemStrategy is propagated to the Multibranch projects

---

src/main/java/jenkins/branch/MultiBranchProjectFactory.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/jenkins/branch/OrganizationFolderTest.java

[JENKINS-34246](https://issues.jenkins-ci.org/browse/JENKINS-34246)
@reviewbybees

[JENKINS-34246] Fix MultiBranchProjectFactory API to allow deletion or update of existing children

---

pom.xml
src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java
src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java

[JENKINS-34239](https://issues.jenkins-ci.org/browse/JENKINS-34239)
Amends #30 by fixing the reverse case.
@reviewbybees

[JENKINS-34239] JENKINS-33106 fix was sensitive to plugin installation ordering

---

pom.xml
src/main/java/jenkins/branch/BranchSource.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/resources/jenkins/branch/Messages.properties

[JENKINS-38987 Follow-up] Pick up SCMxxx.getPronoun()

---

pom.xml
src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java

[JENKINS-38960 Follow-up] Switch to IconSet

---

src/main/java/jenkins/branch/SimpleViewBranchFilter.java

[FIXED JENKINS-39026] Add an abstract base class for simple ViewBranchFilter

---

src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.properties

@reviewbybees esp. @daniel-beck who requested this

Clarify that CHANGE_* properties may or may not be set

---

pom.xml

Push people to read [release notes](https://wiki.jenkins-ci.org/display/JENKINS/Branch+API+Plugin#BranchAPIPlugin-Version1.11%28Sep23%2C2016%29) for #50.
@reviewbybees

[JENKINS-34564] compatibleSinceVersion=1.11

---

pom.xml

Add plugin dependency as first level dependency.
@reviewbybees @stephenc

[JENKINS-39816] Fix PCT against >= 2.16

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java
src/test/java/integration/harness/BasicBranchProjectFactory.java
src/test/java/integration/harness/BasicBranchProperty.java

I suspect we should have some test failures as these are new test cases based on some manual testing I have been doing
@reviewbybees

More tests

---

src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/19
@reviewbybees

Pick up navigator IDs

---

src/main/java/jenkins/branch/BranchStatusColumn.java

@reviewbybees (found during some other stuff)

BranchStatusColumn should not be exposed to users

---

pom.xml
src/test/java/integration/EventsTest.java

See [JENKINS-40828](https://issues.jenkins-ci.org/browse/JENKINS-40828)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/22
@reviewbybees

[JENKINS-40828] Add a failure mode test

---

pom.xml
src/main/java/jenkins/branch/BranchProjectFactory.java

See [JENKINS-40829](https://issues.jenkins-ci.org/browse/JENKINS-40829)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/23
@reviewbybees

[JENKINS-40829] Implement extension point for JENKINS-40829 support]

---

pom.xml
src/main/java/jenkins/branch/ItemColumn.java
src/main/java/jenkins/branch/MultiBranchProjectViewHolder.java
src/main/java/jenkins/branch/OrganizationFolderViewHolder.java
src/main/resources/jenkins/branch/ItemColumn/column.jelly
src/main/resources/jenkins/branch/ItemColumn/columnHeader.jelly
src/main/resources/jenkins/branch/Messages.properties

See [JENKINS-40832](https://issues.jenkins-ci.org/browse/JENKINS-40832)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/20 and https://github.com/jenkinsci/scm-api-plugin/pull/21
@reviewbybees

[FIXED JENKINS-40832] Primary branches should have their name in bold

---

src/main/java/jenkins/branch/LocalizedViewsTabBar.java
src/main/java/jenkins/branch/MultiBranchProject.java

Make compilable using JDK 9 javac

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/EventsTest.java

See [JENKINS-41125](https://issues.jenkins-ci.org/browse/JENKINS-41125)
@reviewbybees

[JENKINS-41125] Update events to a branch with a name that gets mangled do not get processed

---

src/main/java/jenkins/branch/Branch.java
src/test/java/jenkins/branch/BranchTest.java

See [JENKINS-41209](https://issues.jenkins-ci.org/browse/JENKINS-41209)
@reviewbybees

[JENKINS-41209] Null Pointer Exception when deserializing during upgrade

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/24
See [JENKINS-41121](https://issues.jenkins-ci.org/browse/JENKINS-41121)
@reviewbybees

[JENKINS-41121] Use the SCMHeadMigration API

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

See [JENKINS-41517](https://issues.jenkins-ci.org/browse/JENKINS-41517)
@reviewbybees

[JENKINS-41517] More consistent logging

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

[JENKINS-41068](https://issues.jenkins-ci.org/browse/JENKINS-41068)
@reviewbybees

[JENKINS-41068] When deleting a branch project, the root dir was recreated

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/java/jenkins/branch/RewindableFileOutputStream.java
src/main/java/jenkins/branch/RewindableRotatingFileOutputStream.java

See [JENKINS-41883](https://issues.jenkins-ci.org/browse/JENKINS-41883)
- Safe to make these methods `synchronized` as all the events get processed on a separate thread pool
@reviewbybees

[FIXED JENKINS-41883] Append global log on open

---

src/main/java/jenkins/branch/ItemColumn.java
src/main/resources/jenkins/branch/ItemColumn/column.jelly

See [JENKINS-41927](https://issues.jenkins-ci.org/browse/JENKINS-41927)
@reviewbybees

[FIXED JENKINS-41927] Orphaned branched should have name in strikethrough

---

pom.xml
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java

See [JENKINS-42000](https://issues.jenkins-ci.org/browse/JENKINS-42000)
@reviewbybees

[JENKINS-42000] Communication errors in organization scanning should not delete all everything

---

src/main/java/jenkins/branch/MultiBranchProjectFactory.java

Allow implementers to throw IOException and InterruptedException

---

pom.xml
src/test/java/integration/EventsTest.java

[JENKINS-42009](https://issues.jenkins-ci.org/browse/JENKINS-42009)
- Bump plugin versions for PCT.
- Make some tests more realistic.
@reviewbybees @stephenc

[JENKINS-42009] Fix PCT for 2.32.2

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/EventsTest.java

- Two have to be ignored for now as they are currently failing (as expected due to 8fe73fc838dd944544d5f0f575dc54c61615a5f8 making event processing single threaded)
@reviewbybees

Add some tests for concurrent events

---

src/main/java/jenkins/branch/MultiBranchProject.java

See [JENKINS-42234](https://issues.jenkins-ci.org/browse/JENKINS-42234)
@reviewbybees

[FIXED JENKINS-42234] Add the isMatch guard

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java

Downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/86
See https://issues.jenkins-ci.org/browse/JENKINS-42151
@reviewbybees

[JENKINS-42151] Pick up API changes

---

src/main/java/jenkins/branch/MultiBranchProjectViewHolder.java
src/main/java/jenkins/branch/OrganizationFolderViewHolder.java

See [JENKINS-37364](https://issues.jenkins-ci.org/browse/JENKINS-37364)
Before:
After:
@reviewbybees

[JENKINS-37364] Tabs should indicate the number of items they have

---

src/main/java/jenkins/branch/TaskNounUiTextProvider.java
src/main/resources/jenkins/branch/Messages.properties

Downstream of https://github.com/jenkinsci/jenkins/pull/2772
See [JENKINS-34522](https://issues.jenkins-ci.org/browse/JENKINS-34522)
@reviewbybees

[JENKINS-34522] Implement an AlternativeUiTextProvider for AbstractItem.TASK_NOUN

---

src/test/java/integration/harness/BasicDummyStepBranchProperty.java

Looking for
BRANCH_NAME=master
but got
BRANCH_NAME='master'
(Better still might be to use a non-native `TestBuilder`.)
@reviewbybees

EnvironmentTest failed on Ubuntu

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java

See [JENKINS-42511](https://issues.jenkins-ci.org/browse/JENKINS-42511)
Downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/92
@reviewbybees

[JENKINS-42511] Add a test to verify root cause

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/resources/jenkins/branch/Messages.properties

See [JENKINS-34691](https://issues.jenkins-ci.org/browse/JENKINS-34691)
Downstream of https://github.com/jenkinsci/jenkins/pull/2782
@reviewbybees

[JENKINS-34691] Adopt proposed veto mechanism

---

pom.xml
src/main/java/jenkins/branch/BranchEventCause.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/resources/jenkins/branch/BranchEventCause/description.jelly
src/main/resources/jenkins/branch/BranchEventCause/description.properties

[JENKINS-41736] Leverage the new event description API to expose event descriptions

---

src/main/java/jenkins/branch/Timeout.java
src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

[JENKINS-44784](https://issues.jenkins-ci.org/browse/JENKINS-44784)
Amends #50. Half of this is akin to https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/30.
@reviewbybees

[JENKINS-44784] Ensure workspace cleanup for deleted branch projects proceeds asynchronously, and will time out if the agent is stuck

---

pom.xml
src/main/java/jenkins/branch/MetadataActionFolderIcon.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

See [JENKINS-45322](https://issues.jenkins-ci.org/browse/JENKINS-45322)
Downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/101
@reviewbybees

[JENKINS-45322] Prevent event processing when disabled

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

[JENKINS-45322] Follow-up to @jglick comments

---

src/main/java/jenkins/branch/BranchBuildStrategy.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/EventsTest.java

See [JENKINS-47308](https://issues.jenkins-ci.org/browse/JENKINS-47308)
@reviewbybees

[FIXED JENKINS-47308] Add the ability for branch build strategies to consider the revision

---

src/main/java/jenkins/branch/BranchBuildStrategyDescriptor.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/resources/jenkins/branch/BranchSource/config.jelly
src/main/resources/jenkins/branch/BranchSource/help-buildStrategies.html
src/main/resources/jenkins/branch/OrganizationFolder/configure-entries.jelly
src/main/resources/jenkins/branch/OrganizationFolder/help-buildStrategies.html

See [JENKINS-43711](https://issues.jenkins-ci.org/browse/JENKINS-47311)
@reviewbybees

[FIXED JENKINS-47311] Fix the broken form submission and add the missing form support for org folders

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java

See [JENKINS-48536](https://issues.jenkins-ci.org/browse/JENKINS-48536)

[FIXED JENKINS-48536] OrganizationFolder should ensure MultibranchProject calls SCMSource.afterSave()

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

Adds some diagnostics to #129.

More logging for JENKINS-2111

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

Amends #129 to fix [JENKINS-54640](https://issues.jenkins-ci.org/browse/JENKINS-54640). Just mixed up key and value, sigh.

[JENKINS-54640] Index collision check was not working

---

src/main/java/jenkins/branch/OverrideIndexTriggersJobProperty.java

1. load /directive-generator/
2. directive: options
3. add build discarder
4. add override index triggers

Drop inappropriate period

---

pom.xml

Supersedes #57. Picks up https://github.com/jenkinsci/git-client-plugin/pull/381.

Updating some test deps

---

pom.xml
src/main/java/jenkins/branch/PrimaryBranchHealthMetric.java
src/main/resources/jenkins/branch/PrimaryBranchHealthMetric/help.html
src/test/java/jenkins/branch/PrimaryBranchHealthMetricTest.java

https://issues.jenkins-ci.org/browse/JENKINS-56903

[JENKINS-56903] Adds a health metric that reports only the primary branch

---

pom.xml
src/main/java/jenkins/branch/OrganizationChildHealthMetricsProperty.java
src/main/java/jenkins/branch/OrganizationChildOrphanedItemsProperty.java
src/main/java/jenkins/branch/OrganizationChildTriggersProperty.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/java/jenkins/branch/OrganizationFolderProperty.java
src/main/java/jenkins/branch/OrganizationFolderPropertyDescriptor.java
src/main/java/jenkins/branch/PrimaryBranchHealthMetric.java
src/main/resources/jenkins/branch/Messages.properties
src/main/resources/jenkins/branch/OrganizationChildHealthMetricsProperty/config.jelly
src/main/resources/jenkins/branch/OrganizationChildOrphanedItemsProperty/Inherit/config.jelly
src/main/resources/jenkins/branch/OrganizationChildOrphanedItemsProperty/config.jelly
src/main/resources/jenkins/branch/OrganizationChildOrphanedItemsProperty/help-strategy.html
src/main/resources/jenkins/branch/OrganizationChildTriggersProperty/config.jelly
src/main/resources/jenkins/branch/OrganizationChildTriggersProperty/help-enforce.html
src/test/java/jenkins/branch/OrganizationChildHealthMetricsPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildOrphanedItemsPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildTriggersPropertyTest.java

https://issues.jenkins-ci.org/browse/JENKINS-56917

[JENKINS-56917] Implementation of extension point to enable org folders to decorate their children

---

pom.xml
src/main/resources/jenkins/branch/MultiBranchProject/orphanedItemStrategyDescription.jelly
src/main/resources/jenkins/branch/MultiBranchProject/orphanedItemStrategyDescription.properties
src/main/resources/jenkins/branch/OrganizationFolder/orphanedItemStrategyDescription.jelly
src/main/resources/jenkins/branch/OrganizationFolder/orphanedItemStrategyDescription.properties

Downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/128 
Bumped some other dependencies to make hpi:run work.
Default text:
Organisation Folder text:
Multibranch pipeline:

[JENKINS-48452] Explain the orphaned item strategy in a contextual way

---

src/main/java/jenkins/branch/BaseEmptyView.java
src/main/java/jenkins/branch/BranchProperty.java
src/main/java/jenkins/branch/DeadBranchIndicatorAction.java
src/main/java/jenkins/branch/DescriptionColumn.java
src/main/java/jenkins/branch/DescriptorOrder.java
src/main/java/jenkins/branch/ItemColumn.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/MultiBranchProjectDescriptor.java
src/main/java/jenkins/branch/MultiBranchProjectFactory.java
src/main/java/jenkins/branch/NoTriggerBranchProperty.java
src/main/java/jenkins/branch/NoTriggerOrganizationFolderProperty.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/java/jenkins/branch/OrganizationFolderProperty.java
src/main/java/jenkins/branch/OverrideIndexTriggersJobProperty.java
src/main/java/jenkins/branch/RateLimitBranchProperty.java
src/main/java/jenkins/branch/SimpleViewBranchFilter.java
src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/NameEncoderTest.java
src/test/java/jenkins/branch/PrimaryBranchHealthMetricTest.java

Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Do some code spring cleaning

Cleanup deprecated code

---

src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java
src/main/java/jenkins/branch/MultiBranchProject.java

Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
These are well old TODOs so clean them up and inherit their documentation

Fix some override TODOs

---

.mvn/extensions.xml
pom.xml

Picks up https://github.com/jenkinsci/incrementals-tools/pull/16, so I can test #209 while waiting for it to be released.

[JENKINS-58716] Make Incrementals artifacts friendly to PCT

---

src/main/java/jenkins/branch/PrimaryBranchHealthMetric.java
src/test/java/integration/harness/HealthReportingBranchProjectFactory.java
src/test/java/integration/harness/HealthReportingMultiBranchProject.java
src/test/java/integration/harness/MockHealthReportBuildStep.java
src/test/java/jenkins/branch/PrimaryBranchHealthMetricTest.java

See https://issues.jenkins-ci.org/browse/JENKINS-59786

[FIXED JENKINS-59786] Report all the health reports of the primary branch, not just the worst one

---

README.md
pom.xml
src/main/resources/jenkins/branch/BranchSource/config.jelly
src/main/resources/jenkins/branch/NamedExceptionsBranchPropertyStrategy/config.jelly
src/main/resources/jenkins/branch/OrganizationChildOrphanedItemsProperty/config.jelly
src/main/resources/jenkins/branch/OrganizationFolder/configure-entries.jelly
src/main/resources/lib/branch-api/blockWrapper.jelly
src/main/resources/lib/branch-api/branchSourceBody.jelly
src/main/resources/lib/branch-api/branchSourceSelector.jelly
src/main/resources/lib/branch-api/entryWrapper.jelly
src/main/resources/lib/branch-api/rowWrapper.jelly

cc @oleg-nenashev @fqueiruga @dwnusbaum 
for it to work fully it needs https://github.com/jenkinsci/cloudbees-folder-plugin/pull/165
Note: there's still other plugins (at least github-branch-source and workflow-multibranch) that need fixing that are causing JS errors but I couldn't see any actual problems.

JENKINS-64069 Fix compat with core 2.264

---

Jenkinsfile

Preparation for https://github.com/jenkinsci/branch-api-plugin/pull/228

Test core versions based on pom

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

Use the predicate form to avoid checking ACLs when possible

Use predicate form of getItems() provided by folders plugin

---

pom.xml

Update to LTS 2.277.x line

---

src/main/java/jenkins/branch/OrganizationFolder.java

`OganizationFolder` lacks a `Symbol` annotation. This PR adds the symbol

Add missing symbol in Organization Folder class

---

src/main/java/jenkins/branch/MultiBranchProject.java

Reduce logging level of branch indexing at it floods the Jenkins log.
---------------------------------

Reduce logging level of branch indexing

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

commit 2dae2ca429b155c43f20d3 added a workaround that is no longer necessary in recent versions of SpotBugs.

Remove no longer necessary workaround

---

src/main/resources/jenkins/branch/ItemColumn/column.jelly

Addresses [JENKINS-72026](https://issues.jenkins.io/browse/JENKINS-72026)
Checked on the following browsers with versions:
1. Jenkins-core:2.426.1, Firefox: 122.0.1, Linux:6.1.0-kali9-amd64
2. Jenkins-core:2.426.1, Chrome: 120.0.6099.62, Linux:6.1.0-kali9-amd64
3. Jenkins-core:2.426.1, Chrome: 117.0.5938.62, MacOS Sonoma
If someone can also test on your own system if the error is gone or not.
```[tasklist]
```

[JENKINS-72026] Fix jumping icons in narrow view

---

src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/message.jelly

[drop_yui] use jenkins button

---

src/test/java/integration/MigrationTest.java

Migrate from deprecated functionality to non-deprecated equivalents.
`mvn clean verify`

Clean up `MigrationTest`

---

src/main/java/jenkins/branch/MetadataActionFolderIcon.java
src/main/resources/images/symbols/folder-disabled-outline.svg

Use symbol for disabled folders

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProjectDescriptor.java
src/main/java/jenkins/branch/OrganizationFolder.java

https://github.com/jenkinsci/cloudbees-folder-plugin/pull/480#discussion_r2033609608
https://github.com/jenkinsci/cloudbees-folder-plugin/pull/514

Remove `ChildNameGenerator#recordLegacyName`

---

pom.xml
src/main/java/jenkins/branch/BranchEventCause.java
src/main/java/jenkins/branch/DescriptionColumn.java
src/main/java/jenkins/branch/ItemColumn.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/MultiBranchProjectDisplayNamingStrategy.java
src/main/java/jenkins/branch/NameMangler.java
src/main/java/jenkins/branch/NamedExceptionsBranchPropertyStrategy.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/integration/MigrationTest.java

Migrate from deprecated/EOL Commons Lang 2 to Commons Lang 3.

Migrate from Commons Lang 2 to Commons Lang 3

---

src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

This test introduced in #129 prints the agent log, since there is a special message there that it is nice to look at (though it is not asserted). #200 noted that the log printing is flaky on Windows and tolerated that. #533 deleted that toleration, apparently due to a flake on Windows which was in fact unrelated to the original, thus allowing the test to become flaky again on Linux.
Locally, it did in fact flake pretty often on Linux. This appears to have been due to a race condition: it was disconnecting an agent, but not waiting for it to actually finish disconnecting before trying to reconnect it again. With the modification, it passes 50× locally.
[CloudBees-internal reference](https://cloudbees.atlassian.net/browse/BEE-60293)

Flakiness in `WorkspaceLocatorImplTest#deleteOffline`
