jenkinsci/branch-api-plugin

src/main/java/jenkins/branch/MultiBranchProject.java

Without this, the branch indexing log shows a broken icon in newer Jenkins releases.
https://github.com/jenkinsci/jenkins/commit/42190ed (from @tfennelly) was incompatible since it assumed that Jelly views were rendering one of the classes to which a new method was actually added, but in fact they can be and are used to render other classes via duck typing. `it.buildStatusIconClassName` was thus a poor choice; should have used `it.iconColor.iconClassName`, which would work with anything that already defined `public BallColor getIconColor()` (a reasonably safe assumption since the view was already evaluating `it.iconColor.description`).
@reviewbybees

Need to define getBuildStatusIconClassName for compatibility with 1.576+ t:buildCaption

---

src/main/java/jenkins/branch/MultiBranchProject.java

Led to junk in `indexing.xml` like this:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<jenkins.branch.MultiBranchProject_-BranchIndexing plugin="branch-api@0.2-beta-4">
<actions>
<hudson.model.CauseAction>
<causes>
<hudson.model.Cause_-LegacyCodeCause>
<stackTrace>
<trace>hudson.model.Cause$LegacyCodeCause.&lt;init&gt;(Cause.java:130)</trace>
<trace>jenkins.branch.MultiBranchProject.scheduleBuild(MultiBranchProject.java:2002)</trace>
…
</stackTrace>
</hudson.model.Cause_-LegacyCodeCause>
</causes>
</hudson.model.CauseAction>
</actions>
…
</jenkins.branch.MultiBranchProject_-BranchIndexing>
```

scheduleBuild() uses the deprecated LegacyCodeCause

---

src/main/java/jenkins/branch/BranchPropertyDescriptor.java

In fact this method _is_ used by Java code, in the same source file in fact.

Removing misleading annotation

---

src/main/java/jenkins/branch/RateLimitBranchProperty.java

Needed for proper _Snippet Generator_ behavior in https://github.com/jenkinsci/workflow-plugin/pull/209. Something like https://github.com/jenkinsci/jenkins/pull/1656 would have made this more natural.

JobPropertyDescriptor.newInstance can return null

---

src/main/java/jenkins/branch/MultiBranchProject.java

@recena noticed that in some `workflow-multibranch` tests, `AbstractGitSCMSource.retrieve` was getting null from `getCriteria()`. The reason is that nothing was calling `SCMSource.setOwner`. Normally this is called from `MultiBranchProject.onLoad` or `.submit`, but in the case of test code using `getSourcesList().add(…)` it was not. This patch just ensures that however the sources list is modified, `setOwner` will be called.
@reviewbybees

Ensure that SCMSource.setOwner is called

---

src/main/java/jenkins/branch/BranchNameContributor.java
src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.jelly
src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.properties

[JENKINS-30252](https://issues.jenkins-ci.org/browse/JENKINS-30252)
Could have restricted this to Workflow multibranch, but seemed generally useful.

[JENKINS-30252] Defining environment variable BRANCH_NAME

---

src/main/java/jenkins/branch/MultiBranchProject.java

Otherwise the user is allowed to effectively modify what is supposed to be a completely generated folder.
@reviewbybees esp. @stephenc, @kzantow

Suppress non-read View permissions on MultiBranchProject within OrganizationFolder

---

pom.xml
src/main/java/jenkins/branch/OrganizationFolder.java

Adding a one-day fallback trigger to newly created organization folders, since you normally want some kind of fallback even if there are webhooks.
Also adding it to the child multibranch projects. Ideally this would be something you could configure, somehow, but there is no mechanism for making such configurations currently, so we should at least have a sensible setting.
Downstream of https://github.com/jenkinsci/cloudbees-folder-plugin/pull/22.

Add PeriodicFolderTrigger by default

---

src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/jenkins/branch/OrganizationFolderTest.java
src/test/java/jenkins/branch/harness/MultiBranchImpl.java

[JENKINS-31516](https://issues.jenkins-ci.org/browse/JENKINS-31516)
@reviewbybees

[JENKINS-31516] Run re-index on children on organization re-index

---

src/main/java/jenkins/branch/MultiBranchProjectDescriptor.java
src/test/java/jenkins/branch/harness/MultiBranchImpl.java

`SingleSCMSource`'s config-detail.jelly uses
[`SingleSCMSource.DescriptorImpl#getSCMDescriptors(SCMSourceOwner)`](https://github.com/jenkinsci/scm-api-plugin/blob/7c99d7f705408a457065fa2d9ef89be8b900b805/src/main/java/jenkins/scm/impl/SingleSCMSource.java#L183-L204),
contrary to the Javadoc on the method removed by this commit.
If you were to implement the method removed by this commit, you could make the method always throw an `IllegalStateException` and it would never occur.

Remove useless MultiBranchProjectDescriptor#getSCMDescriptors() API.

---

src/main/java/jenkins/branch/BranchSource.java

[JENKINS-32749](https://issues.jenkins-ci.org/browse/JENKINS-32749)
This PR prevents `NPE` during unserialization in case that a `BranchSource` has a null `SCMSource`. It can happen if an implementation of `SCMSource` is not present (disappears).
@reviewbybees specially @jglick, @amuniz

[JENKINS-32749] Prevent NPE during unserialization of BranchSource

---

pom.xml
src/main/java/jenkins/branch/Branch.java
src/main/java/jenkins/branch/BranchNameContributor.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/7.
Can use https://github.com/cloudbeers/PR-demo/pull/9 as a demo.
@reviewbybees

[JENKINS-33309] Use ChangeRequestAction

---

src/main/java/jenkins/branch/BaseEmptyView.java
src/test/java/jenkins/branch/OrganizationFolderTest.java

[JENKINS-32782](https://issues.jenkins-ci.org/browse/JENKINS-32782)
Corrects handling of view identity which I commented on in #17.
@reviewbybees esp. @stephenc, @kzantow

[JENKINS-32782] Empty view did not show delete link

---

src/main/java/jenkins/branch/BaseEmptyView.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

[JENKINS-34259](https://issues.jenkins-ci.org/browse/JENKINS-34259)
@reviewbybees especially, @kzantow since he worked on `BaseEmptyView`.

[JENKINS-34259] Some links are broken in the Welcome page

---

src/main/java/jenkins/branch/MultiBranchProject.java

https://github.com/jenkinsci/github-branch-source-plugin/pull/53 turned up nothing surprising, so checking why branch indexing is failing to schedule a branch build.
@reviewbybees

Improve logging from branch indexing

---

src/main/java/jenkins/branch/BranchIndexingCause.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/resources/jenkins/branch/BranchIndexingCause/description.jelly

`SCMTriggerCause` is not really appropriate for multibranch projects. For example, it tries to save a polling log, which in fact has bogus text. And the hyperlink is not useful.
@reviewbybees

Switched from SCMTrigger.SCMTriggerCause to BranchIndexingCause

---

pom.xml
src/main/java/jenkins/branch/BranchIndexingCause.java
src/main/java/jenkins/branch/BranchProperty.java
src/main/java/jenkins/branch/NoTriggerBranchProperty.java
src/main/java/jenkins/branch/NoTriggerOrganizationFolderProperty.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/resources/jenkins/branch/Messages.properties
src/main/resources/jenkins/branch/NoTriggerBranchProperty/config.jelly
src/main/resources/jenkins/branch/NoTriggerBranchProperty/help.html
src/main/resources/jenkins/branch/NoTriggerOrganizationFolderProperty/config.jelly
src/main/resources/jenkins/branch/NoTriggerOrganizationFolderProperty/help-branches.html
src/main/resources/jenkins/branch/harness/BranchProjectFactoryImpl/config.jelly
src/test/java/jenkins/branch/NoTriggerBranchPropertyTest.java
src/test/java/jenkins/branch/NoTriggerOrganizationFolderPropertyTest.java
src/test/java/jenkins/branch/harness/BranchProjectFactoryImpl.java
src/test/java/jenkins/branch/harness/MultiBranchImpl.java

[JENKINS-32396](https://issues.jenkins-ci.org/browse/JENKINS-32396)
Supersedes #1, from which it mostly borrows the branch property system (though with a different mechanism for actually suppressing the build).
I debated various approaches for extending the feature to organization folders and could not come up with a very satisfactory answer, so I went with this relatively straightforward system of using a folder property, which seems to work well enough.
The question is whether there is a more general need for defining branch property strategies at the organization folder level. For example, you could imagine a `BranchPropertyStrategyFactory` bound to an `OrganizationFolder` which would define a `BranchPropertyStrategy` on each `BranchSource` in each `MultiBranchProject` child. A simple …

[JENKINS-32396] Option to suppress automatic SCM trigger

---

src/main/java/jenkins/branch/MultiBranchProject.java

[JENKINS-32178](https://issues.jenkins-ci.org/browse/JENKINS-32178)

[JENKINS-32178] Fix broken links to branches from custom views

---

pom.xml
src/main/java/jenkins/branch/NoTriggerBranchProperty.java
src/main/java/jenkins/branch/NoTriggerOrganizationFolderProperty.java
src/main/java/jenkins/branch/OverrideIndexTriggersJobProperty.java
src/main/resources/jenkins/branch/OverrideIndexTriggersJobProperty/config.jelly
src/main/resources/jenkins/branch/OverrideIndexTriggersJobProperty/help.html
src/test/java/jenkins/branch/OverrideIndexTriggersJobPropertyTest.java

[JENKINS-37219](https://issues.jenkins-ci.org/browse/JENKINS-37219)
Works in both directions - disables branch index triggers if set to
false, enables them if set to true and either there's a
NoTriggerBranchProperty applying to the branch or there's a
NoTriggerOrganizationFolderProperty applying to the organization.
Theoretically, the config shouldn't show up for any job type but
multibranch jobs, where it'll only show up in the Snippet Generator anyway.
https://github.com/jenkinsci/workflow-multibranch-plugin/pull/26 will be replaced with an integration test of this in the `properties` step.
cc @reviewbybees esp @jglick

[JENKINS-37219] Add a job property for overriding branch index triggers

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java
src/test/java/jenkins/branch/harness/BranchProjectFactoryImpl.java

[JENKINS-34564](https://issues.jenkins-ci.org/browse/JENKINS-34564)
As opposed to #46, this only touches the workspace paths, not the actual `Item.fullName`; guarantees unique names; and bounds path lengths too.
@reviewbybees

[JENKINS-34564] Safer workspace names for branch projects

---

src/main/java/jenkins/branch/CustomOrganizationFolderDescriptor.java
src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java

[JENKINS-39520](https://issues.jenkins-ci.org/browse/JENKINS-39520)
@reviewbybees

[JENKINS-39520] ExtensionList.removeAll is unimplemented

---

pom.xml
src/main/java/jenkins/branch/DescriptionColumn.java

- We do not need to worry about displayName as that is already on code paths that correctly escape
See [JENKINS-40827](https://issues.jenkins-ci.org/browse/JENKINS-40827)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/21
@reviewbybees

[JENKINS-40827] Fix the escaping in description column

---

src/main/java/jenkins/branch/ItemColumn.java
src/main/resources/jenkins/branch/ItemColumn/column.jelly

When [JENKINS-40876](https://issues.jenkins-ci.org/browse/JENKINS-40876) is fixed, it becomes handy to try displaying the ObjectDisplayName and fall back to the Object Description
The following screenshot shows the PR's title being visible as a tool-tip
Note: It was really *fun* trying to determine how to handle escaping or not of the value. In the end as this is being directly applied to a HTML attribute, it turns out that Jelly does the required escaping for us. If we were providing this as a HTML value then we might need to escape

[JENKINS-40876] Fixes to display of object metadata

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java

See [JENKINS-41255](https://issues.jenkins-ci.org/browse/JENKINS-41255)
@reviewbybees

[JENKINS-41255] Propagate SCMSource id changes when the new SCMSource is identical to the old

---

pom.xml
src/main/java/jenkins/branch/BranchEventCause.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/main/resources/jenkins/branch/BranchEventCause/description.jelly
src/main/resources/jenkins/branch/BranchEventCause/description.properties

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/27
See [JENKINS-41795](https://issues.jenkins-ci.org/browse/JENKINS-41795)
Reports the origin of events, the event logs will now look something like:
And the tooltip for a branch event will include the origin if known:
@reviewbybees

[JENKINS-41795] Report event origins

---

src/main/java/jenkins/branch/NoTriggerBranchProperty.java
src/main/java/jenkins/branch/NoTriggerOrganizationFolderProperty.java

When build is triggered via webhook, the action cause is `BranchEventSource`. Hence the check [here](https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/NoTriggerBranchProperty.java#L72) or [here](https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/NoTriggerOrganizationFolderProperty.java#L90) is bypassed and the answer to `.shouldSchedule` is `true`.

[JENKINS-41980] SCM triggering should also be suppressed for GitHub webhooks

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

jenkinsci/branch-api-plugin#50 added `PATH_MAX`, which defaults to 80.  I assumed that I could set `PATH_MAX` to 20 to enforce a maximum workspace path of 20 characters.  I need somewhere between 15 and 20 character workspace paths due to Windows path limitations documented in [JENKINS-34564](https://issues.jenkins-ci.org/browse/JENKINS-34564).  However, due to [the way the minimize() function uses `PATH_MAX`](https://github.com/jenkinsci/branch-api-plugin/blob/4fdf888d62848cbf6d91255607d39dd71b536653/src/main/java/jenkins/branch/WorkspaceLocatorImpl.java#L95), the effective minimum for `PATH_MAX` is actually 54 characters, which is too many for me.
This pull request reduces the effective minimum of `PATH_MAX` to 12 characters: one for the last character of the mnemonic, one for the "-", …

[JENKINS-34564] Allow workspace paths to be less than 54 characters.

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

[JENKINS-42511](https://issues.jenkins-ci.org/browse/JENKINS-42511)
If you run `workflow-aggregator-plugin/demo/` with this patch as a snapshot in `plugins.txt`, and wait for the `cd` folder to index itself on a timer (rather than initiating that manually), you will see that branch indexing runs _twice_, inexplicably with the same timestamp:
```
Mar 07, 2017 12:08:00 AM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: cd #20170307.000800 branch indexing action completed: SUCCESS in 0.35 sec
Mar 07, 2017 12:08:00 AM jenkins.branch.MultiBranchProject$BranchIndexing run
INFO: cd #20170307.000800 branch indexing action completed: FAILURE in 0.43 sec
```
and this defensive exception gets thrown in the second one. Without it, we silently create a second `WorkflowJob` for the same …

[JENKINS-42511] Make sure we do not attempt to create the same branch project twice

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

Unlike #98 this adds no UI and does not require users to make any configuration changes. It simply interprets `${ITEM_FULLNAME}` as a sanitized path rather than `Item.fullName`.
Also includes a fix for workspace deletion with custom `PATH_MAX` which I noticed; I really needed to fix that before implementing this anyway.
In the longer term, in JENKINS-2111 I have a proposal for a unified system.
@reviewbybees

[JENKINS-38837] Handle custom master workspace directory

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

Would make the error in [JENKINS-45142](https://issues.jenkins-ci.org/browse/JENKINS-45142) more legible.
@reviewbybees

Display stack traces in logs in a more readable order

---

pom.xml

[JENKINS-46957](https://issues.jenkins-ci.org/browse/JENKINS-46957)
- Update to 2.33 parent POM.
- Update dependencies accordingly.
@reviewbybees @stephenc

[JENKINS-46957] Use new parent POM to fix PCT issues

---

src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/integration/EventsTest.java

See [JENKINS-48214](https://issues.jenkins-ci.org/browse/JENKINS-48214)

[FIXED JENKINS-48214] Organization folders should handle events for children that are non-buildable

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/BrandingTest.java

- Should have been specified that SCMSource.fetchActions should not return CauseAction, but we missed that so let's just handle the merge as it is not a major crime
See [JENKINS-48090](https://issues.jenkins-ci.org/browse/JENKINS-48090)

[FIXED JENKINS-48090] Merge CauseActions when scheduling

---

pom.xml
src/main/java/jenkins/branch/BranchBuildStrategy.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/EventsTest.java

See [JENKINS-48535](https://issues.jenkins-ci.org/browse/JENKINS-48535)

[FIXED JENKINS-48535] Allow a BranchBuildStrategy to not build PR-merge revisions where the only change is the target revision

---

src/main/java/jenkins/branch/MultiBranchProject.java

Otherwise you sporadically get an [error in `WorkflowMultiBranchProjectFactoryTest.configuredScriptName`](https://ci.jenkins.io/job/Plugins/job/workflow-multibranch-plugin/job/PR-70/2/testReport/org.jenkinsci.plugins.workflow.multibranch/WorkflowMultiBranchProjectFactoryTest/configuredScriptName/):
```
java.lang.IllegalStateException: no parent set on org.jenkinsci.plugins.workflow.job.WorkflowJob[master]
at hudson.model.AbstractItem.getParent(AbstractItem.java:201)
at hudson.model.AbstractItem.getRootDir(AbstractItem.java:192)
at hudson.model.Items.getConfigFile(Items.java:387)
at hudson.model.AbstractItem.getConfigFile(AbstractItem.java:505)
at hudson.model.AbstractItem.save(AbstractItem.java:500)
at hudson.model.Job.save(Job.java:196)
at …
```

[JENKINS-48890] - Do not call BranchProjectFactory.setOwner(null)

---

pom.xml
src/main/java/jenkins/branch/BranchSource.java
src/main/java/jenkins/branch/MultiBranchProject.java

Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/53, since otherwise you could get a `NotExportableException`.

[JENKINS-50777] Export the SCMSource(s) from a MultiBranchProject

---

src/main/java/jenkins/branch/RateLimitBranchProperty.java

[JENKINS-50561](https://issues.jenkins-ci.org/browse/JENKINS-50561)
I wanted to avoid "throttle" in the symbol, since that's already a
thing over in Throttle Concurrent Builds, and "throttle" means
something different there than it does here.

[FIXED JENKINS-50561] Add rateLimitBuilds symbol

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

[JENKINS-54654](https://issues.jenkins-ci.org/browse/JENKINS-54654)

[JENKINS-54654] WorkspaceLocatorImpl.getWorkspaceRoot did not handle paths using ${ITEM_FULL_NAME} but not ${JENKINS_HOME}

---

pom.xml
src/main/java/jenkins/branch/BranchBuildStrategy.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/EventsTest.java
src/test/java/jenkins/branch/BranchCategoryFilterTest.java

See [JENKINS-56658](https://issues.jenkins-ci.org/browse/JENKINS-56658)

[FIXED JENKINS-56658] BranchBuildStrategy implementations need to be able to log rationale

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

[JENKINS-54968](https://issues.jenkins-ci.org/browse/JENKINS-54968)

[JENKINS-54968] Users may have included a trailing slash in Jenkins.rawWorkspaceDir

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

This issue shows that changing the pronoun on a project in
in order to make some actions by the project more clear is
actually problematic.  
As reasonable fix, this change makes
the indexing use the source pronoun(s) while reverting the
projects to using their original pronouns.
This PR came from discussions around
https://github.com/jenkinsci/github-branch-source-plugin/pull/195
After this change the Multibranch Pipeline looks like this: 
A github organization folder looks like this:

[JENKINS-54992] Do not override pronoun on projects only on their scan

---

Jenkinsfile
pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

Making sure this plugin is constantly checked both building with JDK8 and JDK11.
This goes with the Jenkins Java 11 General Availability announcement made back in March, and we're making a pass to check plugins are looking good on a JDK11.
([to understand the Jenkinsfile content](https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime))
@jenkinsci/java11-support

Java 11 readiness: build both on JDK8 and JDK11

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/jenkins/branch/OrganizationFolderTest.java

In my own life, I am building a Jenkins plugin that adds the ability to generate `OrganizationFolder`s for a user against an SCM server (each of which will then generate `MultiBranchProjects` for each repo, as an `OrganizationFolder` does).
Suppress modify permissions in OrganizationFolder when it is a direct child of a ComputedFolder
=====
The [`MultiBranchProject` detects if it is a child of an `OrganizationFolder`](https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/java/jenkins/branch/MultiBranchProject.java#L776-L797) and hides from users the ability to directly update and delete it, because it is managed programmatically by the `ComputedFolder` aspect of `OrganizationFolder`.
`OrganizationFolder` itself does _not_ do this, so the automatically-generated organization …

Support for programmatically generating OrganizationFolders

---

docs/implementation.adoc
src/main/java/jenkins/branch/BranchBuildStrategy.java
src/main/java/jenkins/branch/BranchProjectFactory.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/EventsTest.java

This is a follow-up of the conversation in #144 
To keep the compatibility with custom plugins which might rely on setRevision being set at build time, I am adding a setLastSeenRevision to also being able to track the current revision.
CC @stephenc @rsandell @Alex-Vol-SV

[JENKINS-38552] Use a lastSeenRevision + lastBuilt

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

Hello,
currently a failed workspace deletion attempt within onOnline will result in node disconnection, because the exception is not handled.
Unfortunately workspace deletion issues are getting more common as users run jobs inside docker containers that might run with a different user than jenkins, thus resulting in files left around in the workspace that jenkins can't delete. While this is a user problem and should be dealt with by ensuring jobs clean up their own files, what would normally be just an annoyance (the workspace files left around) can turn into an outage as the node fails to re-connect if it can't delete a workspace.
So this patch mitigates the issue by preventing onOnline from failing and by warning the operator that there are workspaces requiring manual cleanup (or jobs …

Handle IOException in onOnline when failing to delete workspace, to prevent a node disconnection

---

pom.xml
src/main/java/jenkins/branch/DeadBranchIndicatorAction.java
src/main/resources/jenkins/branch/DeadBranchIndicatorAction/jobMain.jelly
src/main/resources/jenkins/branch/DeadBranchIndicatorAction/summary.jelly

Also had to tweak the dependencies a bit since the introduction of
git 4.0.0-rc broke hpi:run
**Before**
*Job Page*
*Except for the "This job is currently disabled" message which was still there before*
*Build Page*
**After**
*Job Page*
*Build Page*

[JENKINS-49729] Add some css to job and run pages for dead branches

---

src/main/java/jenkins/branch/MultiBranchProject.java

From discussion of with @MarkEWaite here's one attempt at addressing JENKINS-57588.

Attempt to stop build storm on plugin update

---

src/main/java/jenkins/branch/MultiBranchProject.java

In #152 we missed a second use of the variable, so display is wrong.
```
Getting remote pull requests...
‘Jenkinsfile’ found
Met criteria
Changes detected: master (bc1bf622bedeb9a04debfa2236620eb0edac6dc6 → bc1bf622bedeb9a04debfa2236620eb0edac6dc6)
No automatic builds for master
```

Fix missing message variable change

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

After #152 and #153, I decided to refactor this huge method.
This is almost pure refactor, but not quite because of minor bugs I found while refactoring. 
I will call out the non refactor changes
It will be useful to view the diffs for each commit and also to set your diff settings to "Hide whitespace differences". 
Depends on #153.

Refactor for clarity and consistency

---

src/main/java/jenkins/branch/BranchBuildStrategy.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationChildOrphanedItemsProperty.java
src/main/java/jenkins/branch/OrganizationFolder.java

They fail the build when using JDK 11.0.3

Fix JDK 11.0.3 javadoc warnings

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

[JENKINS-58177](https://issues.jenkins-ci.org/browse/JENKINS-58177)
This is pull requests replaces a leading hyphen in shortened workspace paths which lead to various problems in linux bash.
i also had to change another tests which is affected by this.

JENKINS-58177 - replace leading hyphen in mnemonic of ws path

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/UpdatingFromXmlTest.java
src/test/resources/integration/UpdatingFromXmlTest/config.xml

... after `createProjectFromXML` or `updateByXml`.
See [JENKINS-39682](https://issues.jenkins-ci.org/browse/JENKINS-39682?focusedCommentId=369197&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-369197).

[JENKINS-39682] trigger after-save hooks and recalculate

---

src/main/java/jenkins/branch/NameEncoder.java
src/test/java/jenkins/branch/NameEncoderTest.java

See [JENKINS-59756](https://issues.jenkins-ci.org/browse/JENKINS-59756).
Somehow, encoding logic got mixed up in `NameEncoder.decode`, causing all inputs to that method that contained a `%` to have their contents duplicated in addition to not totally decoding special characters. For example, `NameEncoder.decode("test%2Ffoo")` returned `tteesstt%2/Fffoooo`. It looks like this method has been broken since it was added in https://github.com/jenkinsci/branch-api-plugin/pull/72.
I'm not totally sure why we haven't caught this until now. My understanding is that it causes the `name-utf8.txt` file for the computed folders for the branch jobs to double in size every time the job for the branch is loaded. We noticed this because a user got an OOME when the file got so large that the characters in …

[JENKINS-59756] Do not duplicate input in NameEncoder.decode

---

src/test/java/jenkins/branch/BuildRetentionBranchPropertyTest.java

Caused by https://github.com/jenkinsci/jenkins/pull/4042; https://github.com/jenkinsci/jenkins/pull/4247 would have avoided the need for this, but too late now. [Example](https://ci.jenkins.io/job/Tools/job/bom/job/PR-110/4/testReport/jenkins.branch/BuildRetentionBranchPropertyTest/pct_branch_api_2_190_x___decoratesStandardJobByFieldReflectionAccess/):
```
java.lang.IllegalStateException: Jenkins.instance is missing. Read the documentation of Jenkins.getInstanceOrNull to see what you are doing wrong.
at jenkins.model.Jenkins.get(Jenkins.java:772)
at hudson.model.AbstractProject.<init>(AbstractProject.java:262)
at hudson.model.Project.<init>(Project.java:92)
at hudson.model.FreeStyleProject.<init>(FreeStyleProject.java:51)
at jenkins.branch.BuildRetentionBranchPropertyTest.decoratesStandard …
```

Fix PCT failure on 2.190.x

---

pom.xml

Forgot to  update the pom with  the github url

update pom to point to github instead of wiki

---

src/main/java/jenkins/branch/MultiBranchProjectViewHolder.java
src/main/java/jenkins/branch/OrganizationFolderViewHolder.java

This PR:
- Reduces scope of locking for better performance
- Refactors code to reduce `hasPermission` calls by half
This was inspired by a stacktrace we often see:
```
"Handling POST /job/git-org/job/git-repo/ajaxExecutors from 10.148.73.74 : qtp2113273959-23348031 View/ajaxExecutors.jelly ExecutorStepExecution/PlaceholderTask/PlaceholderExecutable/executorCell.jelly" prio=5 BLOCKED
jenkins.branch.MultiBranchProjectViewHolder.getPrimaryView(MultiBranchProjectViewHolder.java:126)
com.cloudbees.hudson.plugins.folder.AbstractFolder$1.primaryView(AbstractFolder.java:266)
hudson.model.ViewGroupMixIn.getPrimaryView(ViewGroupMixIn.java:171)
com.cloudbees.hudson.plugins.folder.AbstractFolder.getPrimaryView(AbstractFolder.java:743)
hudson.model.View.isDefault(View.java:421) …
```

Reduce scope of locks in MultibranchProjectViewHolder and OrganizationFolderViewHolder

---

src/main/java/jenkins/branch/TaskNounUiTextProvider.java

Now that the baseline has JENKINS-34522 access `TASK_NOUN` directly

Follow up to JENKINS-34522

---

pom.xml
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/MultiBranchProjectViewHolder.java

Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Re-implementation of #172 
This PR is on the assumption that jenkinsci/cloudbees-folder-plugin#137 gets merged so we can use the new API and potentially reduce the number of calls to `hasPermission`
We see stacktraces such as:
```
java.lang.String$CaseInsensitiveComparator.compare(String.java:1186)
java.lang.String.compareToIgnoreCase(String.java:1239)
hudson.util.CaseInsensitiveComparator.compare(CaseInsensitiveComparator.java:40)
hudson.util.CaseInsensitiveComparator.compare(CaseInsensitiveComparator.java:34)
jenkins.model.IdStrategy$CaseInsensitive.compare(IdStrategy.java:225)
jenkins.model.IdStrategy.equals(IdStrategy.java:120)
nectar.plugins.rbac.groups.Group.isMatch(Group.java:492) …
```

Use new api to reduce checks

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
The current problem experienced by my team is that if individual nodes have large folders with un-deletable files eg. `node_modules` from a nodejs build the entire exception becomes incredibly large and causes slowdown as the log spam is very large. This is especially a problem if multiple nodes have issues and you are restarting jenkins.
Log the base exception on warning but the details of it is logged on a lower level. This protects the master and if the admin needs to debug this he can also look into finer levels of logging
There is also a logging improvement to pinpoint which node the error comes from as the current error is useless on systems with a large number of nodes.
This is an improvement to the idea in #175

Only log top level exception on WARNING when deleting

---

src/test/java/jenkins/branch/BranchNameContributorTest.java
src/test/java/jenkins/branch/NoTriggerBranchPropertyTest.java
src/test/java/jenkins/branch/NoTriggerOrganizationFolderPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildHealthMetricsPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildOrphanedItemsPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildTriggersPropertyTest.java
src/test/java/jenkins/branch/OverrideIndexTriggersJobPropertyTest.java
src/test/java/jenkins/branch/PrimaryBranchHealthMetricTest.java
src/test/java/jenkins/branch/RateLimitBranchPropertyTest.java

- Cleanup some tests with using the older now NOOPed `doYank()` method
- Rewrite the delay calculation in RateLimitBranchPropertyTest to not be truncated.
- Fix the delay to not be an overly bloated number
Running it in CI to try to reproduce all the test flakes

Cleanup tests

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

If `locate` hangs, it can be hard to figure out what job is being processed.

More helpful Thread.name during WorkspaceLocatorImpl.Deleter.CleanupTask

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

`load` makes a network connection and transfers a text file, so better to cache its result between calls so long as the agent remains online, and also remember what we already `save`d.

Cache index of WorkspaceLocatorImpl.load/save

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

Looking at a thread dump from CloudBees Core (not that it likely matters) like
```
Handling GET /…/ from … View/index.jelly View/sidepanel.jelly
java.lang.Thread.State: BLOCKED (on object monitor)
at com.cloudbees.opscenter.client.cloud.StandardCloudSlave.getNodeUsage(StandardCloudSlave.java:312)
- waiting to lock <0x…> (a com.cloudbees.opscenter.client.cloud.StandardCloudSlave)
at com.cloudbees.opscenter.client.cloud.StandardCloudSlave.getNumExecutors(StandardCloudSlave.java:381)
at com.cloudbees.opscenter.client.cloud.OperationsCenterCloudComputer.isAcceptingTasks(OperationsCenterCloudComputer.java:71)
at hudson.model.Computer.getIconClassName(Computer.java:753)
"Executor #0 for … : executing PlaceholderExecutable:ExecutorStepExecution.PlaceholderTask{…}" …
java.lang.Thread.State: …
```

WorkspaceLocatorImpl should not use Node instances as monitors

---

pom.xml
src/main/java/jenkins/branch/BuildRetentionBranchProperty.java
src/main/java/jenkins/branch/DefaultBranchPropertyStrategy.java
src/main/java/jenkins/branch/NamedExceptionsBranchPropertyStrategy.java
src/main/java/jenkins/branch/NoTriggerBranchProperty.java
src/main/java/jenkins/branch/RateLimitBranchProperty.java
src/main/java/jenkins/branch/UntrustedBranchProperty.java
src/test/java/jenkins/branch/BranchCategoryFilterTest.java

adding symbol annotations to `BranchProperty` and `BranchPropertyStrategy` subclasses to make databinding easier

add symbol annotations to BranchProperty and BranchPropertyStrategy subclasses

---

src/test/java/integration/EventsTest.java
src/test/java/jenkins/branch/WorkspaceLocatorImplTest.java

Compatibility with @calvinpark’s https://github.com/jenkinsci/jenkins/pull/4684. Noticed in #199.

[JENKINS-61956] Adapt test to stricter enforcement of createFreeStyleProject arg

---

src/test/java/jenkins/branch/CustomOrganizationFolderDescriptorTest.java
src/test/java/jenkins/branch/OrganizationChildHealthMetricsPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildOrphanedItemsPropertyTest.java
src/test/java/jenkins/branch/OrganizationChildTriggersPropertyTest.java
src/test/java/jenkins/branch/OrganizationFolderTest.java
src/test/java/jenkins/branch/matchers/Extracting.java
src/test/java/jenkins/branch/matchers/ExtractingTest.java

Fix the PCT failures unearthed in https://github.com/jenkinsci/bom/pull/179
To do:

Fix PCT failures

---

src/main/java/jenkins/branch/OrganizationFolder.java
src/test/java/jenkins/branch/OrganizationFolderTest.java

Test from #45 is fragile.
```
java.lang.AssertionError: expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at jenkins.branch.OrganizationFolderTest.deletedMarker(OrganizationFolderTest.java:142)
```
due to `WorkflowMultiBranchProjectFactory` (i.e., **from Jenkinsfile**) spuriously recognizing the test “repository”.

OrganizationFolderTest.deletedMarker failed in PCT with megawar incl. workflow-multibranch

---

src/test/java/jenkins/branch/RateLimitBranchPropertyTest.java

Test from #58, flaking in https://ci.jenkins.io/job/Tools/job/bom/job/PR-179/29/testReport/junit/jenkins.branch/RateLimitBranchPropertyTest/pct_branch_api_2_176_x___rateLimitsBlockBuilds_maxRate/ :
```
java.lang.AssertionError: 
At least the rate implied delay but no more than 500ms longer
Expected: (a value equal to or greater than <3400L> and a value less than or equal to <4100L>)
but: a value less than or equal to <4100L> <6282L> was greater than <4100L>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at jenkins.branch.RateLimitBranchPropertyTest.rateLimitsBlockBuilds(RateLimitBranchPropertyTest.java:201)
at jenkins.branch.RateLimitBranchPropertyTest.rateLimitsBlockBuilds_maxRate(RateLimitBranchPropertyTest.java:132)
```
Seems inherently sensitive to timing on the …

Flake in RateLimitBranchPropertyTest.rateLimitsBlockBuilds_maxRate

---

src/main/java/jenkins/branch/DescriptionColumn.java
src/main/resources/jenkins/branch/DescriptionColumn/column.jelly

This PR adds the support for formating HTML tags in the description column properly.
Before:
After:

Support markup formatter in description column

---

src/test/java/jenkins/branch/OrganizationFolderTest.java

Amends #145 for PCT compatibility with https://github.com/jenkinsci/jenkins/pull/4848.

Avoid TestingAuthenticationToken; use createDummySecurityRealm

---

Jenkinsfile
src/test/java/jenkins/branch/ParameterDefinitionBranchPropertyTest.java

The new test case fails with
```
java.lang.IllegalArgumentException: Unable to convert to class java.lang.Object
at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:738)
at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
at org.kohsuke.stapler.RequestImpl.injectSetters(RequestImpl.java:834)
at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:784)
at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:678)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class hudson.model.ParameterDefinition from {"name":"CHOOSE","choices":"a\nb","description":"choose one","stapler-class":"hudson.model.ChoiceParameterDefinition","$class":"hudson.model.ChoiceP …
```

[JENKINS-61438] Demonstration of IAE from Stapler

---

src/test/java/jenkins/branch/RateLimitBranchPropertyTest.java

Follows up #202. Flake noticed in https://github.com/jenkinsci/bom/pull/301:
```
java.lang.AssertionError: 
At least the rate implied delay but no more than 500ms longer
Expected: (a value equal to or greater than <3400L> and a value less than or equal to <4100L>)
but: a value equal to or greater than <3400L> <3342L> was less than <3400L>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at jenkins.branch.RateLimitBranchPropertyTest.rateLimitsConcurrentBuilds(RateLimitBranchPropertyTest.java:292)
```

RateLimitBranchPropertyTest.rateLimitsConcurrentBuilds is flaky too

---

src/test/java/jenkins/branch/OrganizationFolderTest.java

Fixes the error seen in https://github.com/jenkinsci/bom/pull/308 by applying the idiom from #199 to #160.

Fix OrganizationFolderTest.verifyBranchPropertiesAppliedOnNewProjects in PCT

---

src/main/resources/jenkins/branch/BranchSource/config.jelly

#226 accidentally dropped a `colspan` attribute, breaking the appearance of the `BranchSource` config page. We should fix that and release a fIx before we merge #228 otherwise users running old versions of core will have to update core for the issue to be fixed.
Before this PR:
After this PR:

Fix appearance of branch source configuration on Jenkins 2.263 and older

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

Noticed in https://github.com/jenkinsci/mercurial-plugin/pull/149 that the `AbortException` gets a stack trace printed (which is wrong—it is a user error) even though https://github.com/jenkinsci/cloudbees-folder-plugin/blob/3afb5acfeeca5a89cf97edc88e8d497b327667c3/src/main/java/com/cloudbees/hudson/plugins/folder/computed/FolderComputation.java#L171-L174 was going to print it politely at the end of the branch indexing log.
You should only print a stack trace if you are _not_ rethrowing an exception.

Do not printStackTrace on an exception you are going to rethrow

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/test/java/integration/UpdatingFromXmlWithDisabledFlagTest.java

This pull request adds a feature flag to allow users to disable a very annoying and serious issue when Jenkins contains many jobs and uses Bitbucket or Github with Job DSL plugin.
Be disabling this setting it will avoid causing hundreds of unnecessary calls and then get to the API rate limit of Bitbucket or Github.
This PR will replace the need for #225.
It also closes this issue on Jenkins https://issues.jenkins.io/browse/JENKINS-63344?attachmentViewMode=list.

[JENKINS-63344] Add a feature flag to be able to disable running SCM branch source scanning when job XMLs are updated

---

src/main/java/jenkins/branch/BranchNameContributor.java
src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.properties
src/test/java/jenkins/branch/BranchNameContributorTest.java

Instead of setting "false" in cases where the branch isn't a primary
branch, don't set the variable at all.
The goal is to make using the value easier and less error-prone. Since
the string "false" is truthy in most contexts, e.g. in
Groovy/Jenkinsfile pipelines and related scripts, its use can lead to
unexpected behavior if evaluated in a condition without first performing
an explicit type conversion.
Additionally, it's already a common practice among most consumers of
such "Boolean" environment variables to treat a nonempty value as an
indication of truth. (cf. the `CI` environment variable)
Related: #236.

Tweak semantics for BRANCH_IS_PRIMARY env var

---

src/main/resources/lib/branch-api/branchSourceBody.jelly

The change proposed addresses Mark's comment on my [core PR](https://github.com/jenkinsci/jenkins/pull/6280#issuecomment-1043356722) about the broken help icon.
Edit: To note, this will only work on my core PR, if someone tests that on the current weekly.

Fix missing help button on modern Jenkins versions

---

src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/OrganizationFolder.java

Previously each log file was limited to 33KB and 5 files.
On our busy Jenkins instance we only got 15 minutes worth of logs before
they were rotated out.
It would be good for this to be increased to make analysis of issues
easier
see https://issues.jenkins.io/browse/JENKINS-68116

JENKINS-68116 Increase log size limit

---

.mvn/extensions.xml
pom.xml

Adapting to https://github.com/jenkinsci/plugin-pom/pull/633 which was released in [4.50](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.50).

Update plugin parent POM

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

[First PR](https://github.com/jenkinsci/branch-api-plugin/pull/214) The first PR i made was intended to resolve the issue which was caused by 'onDeleted'. After having the changes run that the issue wasn't memory related but rather the OOM exception was raised after the agents disconnected. 
So this is the second draft trying to resolve this issue, so far this has been running for more than 2 weeks without any issues.
The idea is to let the users set a limit for how many threads can run in Jenkins, and if that cap is reached the 'onDeleted' will wait with spawning new threads until the limit isn't reached. 
This might be a crude way to implement this check, it might be better to try at set the limit on only the plugin instead of Jenkins instance.
I'm hoping this might be useful as is and …

Add the ability to limit the number of cleanup threads

---

pom.xml
src/test/java/jenkins/branch/BranchCategoryFilterTest.java

https://github.com/jenkinsci/branch-api-plugin/pull/362#issuecomment-1508991900 reported by @MarkEWaite in https://github.com/jenkinsci/branch-api-plugin/pull/353#issuecomment-1508430457. I find Mockito-based tests to be both difficult to maintain and of low value in preventing genuine regressions, so I am not inclined to spend more time debugging.

Update parent POM, ignoring a broken test

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

[JENKINS-60451](https://issues.jenkins.io/browse/JENKINS-60451). As mentioned somewhere in Jira, it would be better for core to just unconditionally switch to the new layout, rather than bugging users to change that setting. See also #258.

[JENKINS-60451] Suppress `JENKINS-2111 path sanitization ineffective` warnings

---

pom.xml
src/test/java/integration/BrandingTest.java

Require Jenkins 2.387.3 or newer so that we can upgrade HTMLUnit from 2.x to 3.x and so that users are not mislead to thinking that we are actively testing older versions of Jenkins.
* Require Jenkins 2.387.3 or newer
* Require git plugin 5.1.0 or newer
Includes changes from:
* #378
* #377 
Supersedes pull requests:
* #375
Compiled plugin and all tests passed.  Will include in my Jenkins installation after an incremental build is available.

Require Jenkins 2.387.3 or newer

---

src/main/java/jenkins/branch/RateLimitBranchProperty.java
src/test/java/jenkins/branch/RateLimitBranchPropertyTest.java

`getId` is not comparable, but `getInQueueSince` is.
This also adds a `LoggerRule` to the test class to make the test output more readable.
cc @jglick 
```[tasklist]
```

`RateLimitBranchProperty`: Fix checking queue for other items tied to the same task

---

.mvn/extensions.xml
Jenkinsfile

Java 21 released Sep 19, 2023. We'd like to announce full support for Java 21 in early October and would like the most used plugins to be compiling and testing with Java 21. The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.
This pull request also includes pull requests:
* #387
* #401
* #406
Confirmed that tests pass on Java 21.

Test with Java 21

---

pom.xml
src/main/resources/lib/branch-api/branchSourceSelector.jelly

See https://github.com/jenkinsci/jenkins/pull/8418#discussion_r1337479191
`hetero-list` adjunct was removed in  https://github.com/jenkinsci/jenkins/pull/8418
If this adjunct gets called, a large stack trace error should appear in the logs.
adjunct resides in `branchSourceSelector.jelly`, which is called by `configure-branches.jelly`, then `configure-entries.jelly` from `MultibranchProject`. Tested under a local instance using a github multibranch folder ~but have not been able to extract any errors~ and was able to generate an error. This PR + https://github.com/jenkinsci/scm-api-plugin/pull/228 removes the error
```[tasklist]
```

remove lib.form.hetero-list.hetero-list

---

pom.xml
src/main/resources/jenkins/branch/MultiBranchProjectEmptyView/main.jelly
src/main/resources/jenkins/branch/OrganizationFolderEmptyView/main.jelly

The change proposed adapts the standard Jenkins icons (ionicons) used in core itself. In this case, the icons look most the same, but ionicons support our theme-ability API and are recommended to use.

Adapt the standard Jenkins icons

---

src/test/java/jenkins/branch/NoTriggerBranchPropertyTest.java

A couple of other places in this test (introduced in #244) were already using `Queue.Item.getFuture` but this one was using `JenkinsRule.configRoundtrip` which seems to have resulted in nondeterministic behavior: https://github.com/jenkinsci/jenkins/pull/8821#issuecomment-1961876826

Make `NoTriggerBranchPropertyTest` pass against 2.446

---

src/main/java/jenkins/branch/OrganizationChildTriggersProperty.java
src/main/java/jenkins/branch/OrganizationFolder.java

This now throws `IllegalArgumentException` in Jenkins core, so no need for an explicit catch.

Remove references to deprecated `ANTLRException`

---

src/main/java/jenkins/branch/OrphanedItemsExtraCleanupProperty.java

add method for deletion of orphaned items

---

src/main/java/jenkins/branch/Branch.java

Exposes a "primary" field to the REST API indicating if the SCM declared the branch as a default/primary branch.
https://issues.jenkins.io/browse/JENKINS-72958
Requires https://github.com/jenkinsci/scm-api-plugin/pull/259 to see PrimaryInstanceMetadataAction class.
Create a multi-branch pipeline branch with "myprinarybranch" as the default branch
http://localhost:8080/jenkins/job/test/job/myprimarybranch/api/xml?tree=property[branch[*]]
```xml
<workflowJob _class="org.jenkinsci.plugins.workflow.job.WorkflowJob">
<property _class="org.jenkinsci.plugins.workflow.multibranch.BranchJobProperty">
<branch>
<action _class="jenkins.scm.api.metadata.PrimaryInstanceMetadataAction"/>
<head _class="jenkins.plugins.git.GitBranchSCMHead">
<name>myprimarybranch</name>
<origin …
```

[JENKINS-72958] expose primary field to REST API

---

src/main/java/jenkins/branch/BuildRetentionBranchProperty.java
src/main/java/jenkins/branch/RateLimitBranchProperty.java
src/main/java/jenkins/branch/UntrustedBranchProperty.java

See https://github.com/jenkinsci/pipeline-plugin/pull/209. These would be used only by https://plugins.jenkins.io/multi-branch-project-plugin/ (deprecated), https://github.com/jenkinsci/freestyle-multibranch-plugin (not on UC), https://github.com/jenkinsci/literate-plugin (ditto), or https://github.com/jenkinsci/yaml-project-plugin (ditto).

Deprecating `BranchProperty`s which do not work with Pipeline

---

src/main/java/jenkins/branch/PropertyMigration.java
src/main/resources/jenkins/branch/Messages.properties
src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/description.jelly
src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/description.properties

The UI of the administrative monitor for `PropertyMigration` seems to be broken since it is missing a display name:
This PR adds a display name and a descripton for the monitor:
I'd be happy to change the label / description to something more elaborate, suggestions are highly welcome.
Manually verified the UI looks as expected.

Add displayName and description to PropertyMigration

---

src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/branch-api-property-migration-disabled-form.js
src/main/resources/jenkins/branch/PropertyMigration/MonitorImpl/message.jelly

* remove redundant inline event handlers in MonitorImpl/message.jelly
* extract inline event handler from MonitorImpl/message.jelly to a separate JavaScript file
https://issues.jenkins.io/browse/JENKINS-73947
Used the following script from JIRA to make the administrative monitor appear:
```groovy
import hudson.model.AdministrativeMonitor
import jenkins.branch.PropertyMigration.MonitorImpl
import jenkins.branch.NoTriggerOrganizationFolderProperty
def monitor = ExtensionList.lookup(AdministrativeMonitor.class).get(MonitorImpl.class)
monitor.add(new NoTriggerOrganizationFolderProperty.PropertyMigrationImpl())
```
https://www.loom.com/share/6ffffdf055be48a7bee6a0fe3c74aeda
https://www.loom.com/share/41c42ef5a87743fba81bb86c9e59bf73
Regarding the removal of `addCrumb` calls. I might be missing …

[JENKINS-73947] Improve CSP compatibility

---

src/main/java/jenkins/branch/ItemColumn.java
src/main/java/jenkins/branch/MultiBranchProject.java
src/main/java/jenkins/branch/MultiBranchProjectDisplayNamingStrategy.java
src/main/resources/jenkins/branch/ItemColumn/column.jelly
src/test/java/integration/CategorizationTest.java
src/test/java/integration/MigrationTest.java

See [JENKINS-60082](https://issues.jenkins.io/browse/JENKINS-60082)
Would be good to get some thoughts on this/if this is the right approach.
Currently doing a survey on what users find useful on the Jenkins Dashboard (https://forms.gle/6XgzRshaF34kn4wLA) and quite a few of the responses list being able to show the pull request title on the dashboard as being useful (and I agree). So thought I'd take a look into that.
The plugin currently displays the pull request title as the `title` attribute of the link, meaning users have to hover over the PR to reveal what it is. This PR changes that so that it displays the title inline.
Branch job dashboard:
Pull requests dashboard:
Project status page:
* PR titles show inline with the PR number
* Tested with GitHub and GitLab
Multi branch pipelines …

[JENKINS-60082] Show pull request title in name column

---

src/main/resources/jenkins/branch/ItemColumn/column.jelly

#476 evidently was not tested in Firefox, which has awkward line break behavior with an `inline-flex`. https://ci.jenkins.io/job/Core/job/jenkins/view/change-requests/ looks like this:
> <img width="720" alt="Screenshot 2024-10-28 at 18 03 27" src="https://github.com/user-attachments/assets/a82e9b74-b03f-4cac-9991-9ef744c9785c">
This changes the column to be more consistent with https://github.com/jenkinsci/jenkins/blob/e1f99468fd81d6aa52dc434fefc6e0420e1cb449/core/src/main/resources/hudson/views/JobColumn/column.jelly#L29.
Tested only with browser dev tools in Firefox so far.
Lazy branch, please delete on merge if GH doesn't do it.

[JENKINS-74783] Fix job name line break behavior in Firefox

---

src/main/java/jenkins/branch/MultiBranchProject.java

See [JENKINS-74777](https://issues.jenkins.io/browse/JENKINS-74777).
As described in the above ticket, use double-checked locking.
As in [this page](https://errorprone.info/bugpattern/DoubleCheckedLocking).
`mvn clean verify`

[JENKINS-74777] Improve locking around `jenkins.branch.MultiBranchProject#getProjectFactory`

---

src/main/resources/jenkins/branch/ItemColumn/column.jelly

[JENKINS-74879](https://issues.jenkins.io/browse/JENKINS-74879) reports that the strikethrough text is no longer displayed when a pull request has been merged or closed.  The strikethrough text is a nice visual indicator that the job is no longer active.  Let's bring it back so that the visual hint is still there for users.
The strikethrough text is displayed on the job page, but not in the table of jobs for each pull request or branch.
Change was originally introduced when pull request titles were enabled by default in the column name.  Refer to:
* https://github.com/jenkinsci/branch-api-plugin/pull/476
Assumed that it is better to drop the jenkins-table__link formatting in the plugin rather than adjust the CSS definion in Jenkins core.  That CSS definition has been in place in Jenkins …

[JENKINS-74879] Use strikethrough on merged pull request name column

---

src/main/java/jenkins/branch/WorkspaceLocatorImpl.java

(amends https://github.com/jenkinsci/branch-api-plugin/pull/237)
The `CleanupTask` of the built-in node were scheduled instantly without acquiring permit from the Semaphore but they were releasing permits, hence creating additional permits over time. Reducing the effectiveness of the limit overtime.
Add the Jenkins `built-in` node to list of nodes to be limited.
NOTES: I guess another solution is to continue not limit the number of `CleanupTask` executed for the `built-in` node but that  looks rather confusing in the first place to have a `CLEANUP_THREAD_LIMIT` that only partially limit the Cleanup tasks..
* Create a Jenkins instance with `-Djenkins.branch.WorkspaceLocatorImpl\$Deleter.CLEANUP_THREAD_LIMIT=1`
* In **Manage Jenkins > Script Console**, execute …

[JENKINS-74975] Fix Semaphore over-allocation of permits / limit all CleanupTasks

---

src/main/java/jenkins/branch/MultiBranchProjectDescriptor.java
src/main/java/jenkins/branch/OrganizationFolder.java

`recordLegacyName` is no longer called from `cloudbees-folder`, so we would like to eventually remove the method there. To do that, first remove the `@Override` annotation here so that we stop depending on the interface declaration in `cloudbees-folder`. Once we feel confident enough that we no longer need to support older versions of `branch-api` from recent versions of `cloudbees-folder`, we can then remove the method there, and once that change propagates here we can then delete the method here.
CI build

Prepare for removal of `recordLegacyName`

---

src/test/java/integration/MigrationTest.java

Prerequisite to https://github.com/jenkinsci/cloudbees-folder-plugin/pull/483. That PR intends to eventually remove `ChildNameGenerator.CHILD_NAME_FILE`, but before we can do that, we have to remove any test assertions that expect it to be present.
- `mvn clean verify` with this PR and without https://github.com/jenkinsci/cloudbees-folder-plugin/pull/483
- `mvn clean verify` without this PR and with https://github.com/jenkinsci/cloudbees-folder-plugin/pull/483 (failed as expected)
- `mvn clean verify` with this PR and with https://github.com/jenkinsci/cloudbees-folder-plugin/pull/483 (passed as expected)

Prepare to eventually remove `ChildNameGenerator.CHILD_NAME_FILE`

---

src/main/java/jenkins/branch/BaseView.java
src/main/java/jenkins/branch/MultiBranchProjectViewHolder.java
src/main/java/jenkins/branch/OrganizationFolderViewHolder.java
src/main/resources/jenkins/branch/BaseView/main.jelly

With https://github.com/jenkinsci/jenkins/pull/10379 (available in 2.513) it is possible for users to define a default views tabbar. When a user chooses a different implementation e.g. from favorite-views plugin, this affects also the views in org and multibranch jobs as they use the ListView from core.
This change introduces a BaseView that brings its own main.jelly ensuring the viewstabbar from the corresponding viewholder is used. The BaseView also unifies the almost identical view implementations.
Verified that with Jenkins 2.513 and favorite-views plugin installed and set as user default, the views tabbar for org or mutlibranch jobs is still the DefaultViewsTabBar.

Add a BaseView to ensure DefaultViewsTabBar is used

---

src/main/resources/jenkins/branch/BranchIndexingCause/detail.jelly

Relates to https://github.com/jenkinsci/jenkins/pull/11128
This PR adds a 'detail' to the experimental run UI, showing the cause of the run in the details row.
* Appears as expected

Add detail for branch indexing cause
